# Generated by Django 3.0.5 on 2020-12-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100, unique=True)),
                ('cluster_name', models.CharField(max_length=20)),
                ('cluster_version', models.CharField(max_length=10)),
                ('server_role', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=16)),
                ('cpus', models.IntegerField()),
                ('memory_in_kb', models.IntegerField()),
            ],
        ),
    ]
